services:
  db:
    image: postgres:15
    container_name: odoo16_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo16_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  odoo:
    image: odoo:16
    container_name: odoo16_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: ${ODOO_DB_HOST}
      PORT: ${ODOO_DB_PORT}
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo16_web_data:/var/lib/odoo
    command: odoo -c /etc/odoo/odoo.conf

volumes:
  odoo16_db_data:
  odoo16_web_data: