from . import base_controller
from . import base_conocimiento_controller
from . import cliente_controller
from . import equipo_controller
from . import mantenimiento_controller
from . import producto_controller
from . import tecnico_controller
from . import tipo_equipo_controller
from . import venta_controller
