[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$8Z5zLqUU4lyrtTZGyPn/nw$8FNbfKyIDAyAYt3ecRa2sub7jHXw.cYM0fcxUqMhoeE2DwpD12S4SA17Hg3ef1CyCKmBAC00seo0QhitsH1N7w
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
log_level = info
xmlrpc_port = 8069

